### ISSUE TITLE
Contact Widget messing up the columns

### ISSUE THREAD

**Issue by JonKings07** [godaddy/wp-contact-widgets#67] opened 2018-12-31 15:25 UTC
Hi Guys.

I just wanted to let you know that when I am using Wordpress since the last version Gutenber, they added a new option called Columns, which it is pretty cool, now you can add blocks and arrange information next to each other,  like photos and text. However I realize that if I add a picture and a text to show one next to the other, the text goes beneath my picture and vice versa. I had to install the Health Check plug in to see what's going, when I deactived the "Contact Widget" plug in by author Godaddy  and Developer Github, my columns started to arrange perfectly as I expected. So I wanted to bring that to your attention, in case you wanna look into it.

**Comment by EvanHerman** [comment] 2019-04-09 12:39
Hi @JonKings07 

This should have been resolved in one of our more recent releases. The stylesheet was being improperly loaded, but that should now be resolved and columns should be working as intended.

Resolved by #69

**Closed by EvanHerman** 2019-04-09 12:39 UTC
Labels: bug, question
